# Zensical Configuration
# Migrated from mkdocs.yml

[project]
site_name = "HansRobo's cheatsheet"
repo_url = "https://github.com/HansRobo/mycheatsheet_mkdocs"
copyright = "Copyright &copy; 2022 HansRobo"

[project.theme.palette]
primary = "amber"

[project.extra]
# Font settings
[project.extra.font]
text = "Noto Sans JP"
code = "Consolas"

[project.extra.search]
language = "en"

[[project.extra.social]]
icon = "fontawesome/brands/twitter"
link = "https://twitter.com/Hans_Robo"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/HansRobo"

[project.extra.analytics]
provider = "google"
property = "G-8WVDNWYEQF"

# Markdown Extensions
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]

[project.markdown_extensions.toc]
permalink = true

# PyMdown Extensions
[project.markdown_extensions."pymdownx.arithmatex"]
generic = true

[project.markdown_extensions."pymdownx.betterem"]
smart_enable = "all"

[project.markdown_extensions."pymdownx.caret"]
[project.markdown_extensions."pymdownx.details"]

[project.markdown_extensions."pymdownx.highlight"]
anchor_linenums = true

[project.markdown_extensions."pymdownx.inlinehilite"]
[project.markdown_extensions."pymdownx.keys"]

[project.markdown_extensions."pymdownx.magiclink"]
repo_url_shorthand = true
user = "squidfunk"
repo = "mkdocs-material"

[project.markdown_extensions."pymdownx.mark"]
[project.markdown_extensions."pymdownx.smartsymbols"]

[project.markdown_extensions."pymdownx.tabbed"]
alternate_style = true

[project.markdown_extensions."pymdownx.tasklist"]
custom_checkbox = true

[project.markdown_extensions."pymdownx.tilde"]

# Third-party extensions
[project.markdown_extensions.mdx_truly_sane_lists]
nested_indent = 4

[project.markdown_extensions."neoteroi.timeline"]
